---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "evictor.fullname" . }}
  labels:
  {{- include "evictor.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
  {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
rules:
  # ------------------------------------------------
  # Volume objects
  # ------------------------------------------------
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
