---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "evictor.fullname" . }}
  labels:
  {{- include "evictor.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
  {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "evictor.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "evictor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
