apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "evictor.name" . }}-config"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
    {{- with .Values.configMapLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}
data:
  config.yaml: | {{- include "evictor.configMap.customConfig" . }}