{{ if .Values.test }}
apiVersion: v1
kind: Secret
metadata:
  name: castai-cluster-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "evictor.labels" . | nindent 4 }}
  {{ if gt (len .Values.commonAnnotations) 0 -}}
  annotations:
    {{- include "evictor.annotations" . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ required "test.apiKey must be provided" .Values.test.apiKey | b64enc | quote }}
{{ end }}
